service: static-site-mailer
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: production
  region: eu-central-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: ["*"]

functions:
  staticSiteMailer:
    handler: handler.staticSiteMailer
    events:
      - http:
          method: post
          path: static-site-mailer
          cors: true
